language: php
php:
  - 7.1
branches:
  only:
    master
before_install:
  - travis_retry composer self-update
  - composer install
jobs:
  include:
    - stage: testing
      script: ./vendor/bin/phpunit ./tests
    - stage: sniffer
      script: ./vendor/bin/phpcs ./src
